version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 0
    labels:
      - "scope/ci-cd"
      - "type/security"
    groups:
      root-python-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    labels:
      - "scope/ci-cd"
      - "type/security"
    groups:
      github-actions:
        patterns:
          - "*"
