repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff-check
        name: ruff (linter)
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        name: ruff (formatter)

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check src
        language: system
