from pathlib import Path

def canonicalize_smiles(smiles: str, remove_mapping: bool = ..., ignore_stereo: bool = ...) -> str: ...
def get_inchi_key(smiles: str, level: str = ...) -> str: ...
def reduce_inchi_key(inchikey: str, level: str) -> str: ...
def molecular_descriptors(smiles: str) -> tuple[int, float, int]: ...
def adapt_candidates_json(
    raw_json: str,
    adapter: str,
    *,
    mode: str = ...,
    target_json: str | None = ...,
    source_key: str | None = ...,
    max_candidates: int | None = ...,
    workers: int = ...,
) -> str: ...
def adapt_route_json(
    raw_json: str,
    adapter: str,
    *,
    mode: str = ...,
    target_json: str | None = ...,
) -> str: ...
def adapter_entries_json(raw_json: str, adapter: str, *, source_key: str | None = ...) -> str: ...
def adapter_cast_result_json(
    raw_json: str,
    adapter: str,
    *,
    mode: str = ...,
    target_json: str | None = ...,
) -> str: ...
def dms_route_length_json(raw_json: str) -> int: ...
def synllama_precursor_map_json(synthesis_string: str, *, mode: str = ...) -> str: ...
def reaction_string_parse_json(route_string: str, adapter: str, *, mode: str = ...) -> str: ...
def synplanner_entries_json(raw_json: str, *, source_key: str | None = ...) -> str: ...
def paroutes_condition_stats_json(route_json: str, statistics_json: str) -> str: ...
def candidate_statistics_json(candidates_json: str) -> str: ...
def collected_candidate_statistics_json(predictions_json: str) -> str: ...
def collected_candidate_statistics_native(predictions: NativePredictions) -> str: ...
def candidate_run_manifest_json(statistics_json: str) -> str: ...
def evaluation_statistics_json(evaluation_json: str) -> str: ...
def evaluation_statistics_native(evaluation: NativeEvaluation) -> str: ...
def bootstrap_distribution_json(values_json: str, n_boot: int, seed: int) -> str: ...
def reliability_flag_json(n: int, probability: float) -> str: ...
def summarize_values_json(
    values_json: str,
    n_boot: int,
    seed: int,
    *,
    alpha: float = ...,
    reliability: bool = ...,
) -> str: ...
def probabilistic_ranking_json(model_values_json: str, n_boot: int, seed: int) -> str: ...
def paired_difference_json(
    values_a_json: str,
    values_b_json: str,
    model_a: str,
    model_b: str,
    metric: str,
    n_boot: int,
    seed: int,
) -> str: ...
def summarize_targets_json(
    targets_json: str,
    tiers_json: str,
    ks_json: str,
    prefix_depths_json: str,
    *,
    metric_label: str = ...,
    match_level: str = ...,
    n_boot: int = ...,
    seed: int = ...,
    workers: int = ...,
) -> str: ...
def check_task_constraints_json(
    route_json: str,
    constraints_json: str,
    stocks_json: str,
    *,
    match_level: str = ...,
) -> str: ...
def target_metric_json(target_json: str, metric: str, *, k: int | None = ...) -> float: ...
def collect_candidates_json(candidates_json: str, task_json: str) -> str: ...
def collect_routes_json(routes_json: str, task_json: str) -> str: ...
def route_path_parse(value: str) -> tuple[str, list[int]]: ...
def route_path_transform(value: str, operation: str, *, index: int | None = ...) -> str: ...
def reactant_order_json(reactants_json: str) -> str: ...
def route_identity_json(
    route_json: str,
    node_kind: str,
    *,
    level: str = ...,
    path: str | None = ...,
    depth: int | None = ...,
    fields_json: str = ...,
) -> str: ...
def route_structure_json(route_json: str, *, molecule_path: str | None = ...) -> str: ...
def ingest_json(
    raw_json: str,
    adapter: str,
    task_json: str,
    *,
    mode: str = ...,
    max_candidates: int | None = ...,
    workers: int = ...,
) -> str: ...
def ingest_native(
    raw_json: str,
    adapter: str,
    task_json: str,
    *,
    mode: str = ...,
    max_candidates: int | None = ...,
    workers: int = ...,
) -> NativePredictions: ...
def ingest_file_native(
    raw_path: Path,
    adapter: str,
    task_path: Path,
    *,
    mode: str = ...,
    max_candidates: int | None = ...,
    workers: int = ...,
) -> NativePredictions: ...
def load_predictions_native(path: Path) -> NativePredictions: ...
def load_evaluation_native(path: Path) -> NativeEvaluation: ...
def score_json(
    predictions_json: str,
    task_json: str,
    stocks_json: str,
    *,
    match_level: str = ...,
    acceptable_route_match: str = ...,
    execution_stats_json: str | None = ...,
    workers: int = ...,
) -> str: ...
def score_native(
    predictions: NativePredictions,
    task_json: str,
    stocks_json: str,
    *,
    match_level: str = ...,
    acceptable_route_match: str = ...,
    execution_stats_json: str | None = ...,
    workers: int = ...,
) -> NativeEvaluation: ...
def score_project_native(
    predictions_path: Path,
    task_path: Path,
    stocks_dir: Path,
    *,
    execution_stats_path: Path | None = ...,
    match_level: str = ...,
    acceptable_route_match: str = ...,
    workers: int = ...,
) -> tuple[NativeEvaluation, str, list[Path]]: ...
def analyze_json(
    evaluation_json: str,
    ks: list[int],
    prefix_depths: list[int],
    *,
    n_boot: int = ...,
    seed: int = ...,
    workers: int = ...,
) -> str: ...
def analyze_native(
    evaluation: NativeEvaluation,
    ks: list[int],
    prefix_depths: list[int],
    *,
    n_boot: int = ...,
    seed: int = ...,
    workers: int = ...,
) -> str: ...
def analyze_file_json(
    evaluation_path: Path,
    ks: list[int],
    prefix_depths: list[int],
    *,
    execution_stats_path: Path | None = ...,
    n_boot: int = ...,
    seed: int = ...,
    workers: int = ...,
) -> str: ...
def run_pipeline_json(
    raw_path: Path,
    benchmark_path: Path,
    stock_path: Path,
    output_dir: Path,
    *,
    stock_name: str | None = ...,
    execution_stats_path: Path | None = ...,
    adapter: str = ...,
    workers: int = ...,
    mode: str = ...,
    max_candidates: int | None = ...,
    match_level: str = ...,
    acceptable_route_match: str = ...,
    ks: list[int] = ...,
    prefix_depths: list[int] = ...,
    n_boot: int = ...,
    seed: int = ...,
) -> str: ...
def verify_manifest_json(
    manifest_path: str,
    root_dir: str,
    *,
    deep: bool = ...,
    output_only: bool = ...,
    lenient: bool = ...,
) -> str: ...
def create_manifest_json(request_json: str) -> str: ...
def hash_file(path: str) -> str: ...
def hash_json(value_json: str) -> str: ...
def write_json_gz_json(path: str, value_json: str) -> None: ...
def write_jsonl_gz_json(path: str, rows_json: str) -> int: ...
def write_lines_gz(path: str, lines: list[str]) -> int: ...
def write_csv_gz(path: str, rows: list[list[str]]) -> int: ...
def read_json_json(path: str) -> str: ...
def read_jsonl_json(path: str, *, skip_empty: bool = ...) -> str: ...
def read_lines_gz(path: str) -> list[str]: ...
def dataset_build_url(base_url: str, segments: list[str]) -> str: ...
def dataset_load_json_url_json(url: str) -> str: ...
def dataset_download_url_to_path(url: str, destination: str) -> None: ...
def dataset_load_sha256sums_json(path: str) -> str: ...
def dataset_download_training_set_json(request_json: str) -> str: ...
def dataset_download_training_data_json(request_json: str) -> list[str]: ...
def dataset_download_hosted_data_json(request_json: str) -> list[str]: ...
def dataset_download_hosted_file(request_json: str) -> str: ...
def dataset_validate_training_request(dataset: str, artifact: str, split: str, format: str) -> None: ...
def dataset_resolve_release(dataset: str, release: str, base_url: str) -> str: ...
def dataset_training_filename(artifact: str, split: str, format: str) -> str: ...
def dataset_training_root(
    dataset: str,
    release: str,
    cache_dir: str | None,
    output_dir: str | None,
) -> str: ...
def dataset_hosted_root(cache_dir: str | None, output_dir: str | None) -> str: ...
def dataset_training_file_matches(
    key: str,
    *,
    artifact: str | None = ...,
    split: str | None = ...,
    format: str | None = ...,
    omit: list[str] = ...,
) -> bool: ...
def dataset_resolve_expected(path: str, url: str, key: str) -> str: ...
def find_route_embeddings_json(
    query_json: str,
    container_json: str,
    *,
    match_level: str = ...,
    allow_leaf_extension: bool = ...,
) -> str: ...
def route_embeds_at_json(
    query_json: str,
    query_path: str,
    container_json: str,
    container_path: str,
    *,
    match_level: str = ...,
    allow_leaf_extension: bool = ...,
) -> str: ...
def subtree_reaction_count_json(route_json: str, molecule_path: str) -> int: ...
def excise_reactions_json(route_json: str, excluded: list[str]) -> str: ...
def deduplicate_routes_json(routes_json: str) -> str: ...
def filter_by_route_type_json(task_json: str, route_type: str) -> str: ...
def clean_and_prioritize_pools_json(primary_json: str, secondary_json: str) -> str: ...
def generate_pruned_routes_json(route_json: str, stock: list[str]) -> str: ...
def route_is_convergent_json(route_json: str) -> bool: ...
def sample_indices(population_size: int, sample_size: int, seed: str) -> list[int]: ...
def sample_stratified_priority_indices(
    grouped_pool_sizes: list[list[int]], target_counts: list[int], seed: str
) -> list[list[tuple[int, int]]]: ...
def training_validation_indices_json(routes_json: str, validation_fraction: float, seed: str) -> list[int]: ...
def adapt_training_routes_json(raw_json: str, dataset: str) -> str: ...
def build_test_route_records_json(dataset: str, routes_json: str, *, route_prefix: str = ...) -> str: ...
def build_test_reaction_records_json(dataset: str, route_records_json: str, *, route_prefix: str = ...) -> str: ...
def build_training_reaction_release_json(route_records_json: str, config_json: str) -> str: ...
def build_training_route_release_json(
    all_routes_json: str,
    all_adaptation_json: str,
    holdout_routes_json: str,
    holdout_adaptation_json: str,
    config_json: str,
) -> str: ...
def audit_route_release_json(release_name: str, all_json: str, training_json: str, validation_json: str) -> None: ...
def audit_single_step_release_json(
    release_name: str,
    all_json: str,
    training_json: str,
    validation_json: str,
    all_rsmi_count: int,
    training_rsmi_count: int,
    validation_rsmi_count: int,
    parent_route_ids: list[str],
) -> str: ...
def build_route_embedding_audit_json(
    release_name: str, containers_json: str, query_sources_json: str, options_json: str
) -> str: ...
def engine_info() -> tuple[str, str, str]: ...

class NativePredictions:
    def json(self) -> str: ...
    def write(self, path: Path) -> None: ...

class NativeEvaluation:
    def json(self) -> str: ...
    def write(self, path: Path) -> None: ...
    def metric_label(self) -> str: ...
