from __future__ import annotations

import argparse
import gzip
import json
import logging
from collections.abc import Callable, Iterable, Iterator, Sequence
from contextlib import contextmanager
from pathlib import Path
from typing import Any

import yaml
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from retrocast import __version__
from retrocast.adapters import ADAPTER_TYPES, DEPRECATED_ADAPTER_SLUGS, get_adapter, normalize_adapter_slug
from retrocast.adapters.base import AdaptMode
from retrocast.chem import get_inchi_key
from retrocast.cli.compare import handle_pareto_frontier
from retrocast.cli.manifest import manifest_sidecar_path, write_manifest
from retrocast.cli.progress import create_cli_progress, estimate_raw_route_entries, quiet_info_logs
from retrocast.cli.report import create_analysis_table, generate_markdown_report
from retrocast.exceptions import ConfigurationError, InputError, RetroCastException, SecurityError
from retrocast.io import (
    load_benchmark,
    load_candidates,
    load_collected_candidates,
    load_evaluation,
    save_analysis_report,
    save_candidates,
    save_collected_candidates,
    save_evaluation,
)
from retrocast.io.blob import load_json_artifact
from retrocast.io.data import load_stock_file
from retrocast.metrics.constraints import TaskConstraintChecker
from retrocast.models.provenance import VerificationReport
from retrocast.models.route import InChIKeyLevel
from retrocast.models.task import Benchmark, TaskConstraints
from retrocast.paths import (
    DEFAULT_DATA_DIR,
    ENV_VAR_NAME,
    get_data_dir_source,
    get_paths,
    resolve_data_dir,
    validate_directory_name,
    validate_filename,
)
from retrocast.typing import InChIKeyStr
from retrocast.utils.logging import configure_script_logging
from retrocast.workflow import (
    adapt_candidates,
    analyze,
    collect_candidates,
    ingest_candidates,
    score,
)
from retrocast.workflow.stats import candidate_statistics, collected_candidate_statistics, evaluation_statistics
from retrocast.workflow.verify import verify_manifest

logger = logging.getLogger(__name__)
console = Console()

VERIFICATION_EXPLANATIONS = {
    "primary": "[bold]Primary Artifact[/bold]: an input file not generated by this workflow; its integrity is a precondition.",
    "graph": "[bold]Graph Discovery[/bold]: finds manifests linked to the target artifact lineage.",
    "phase1": "[bold]Phase 1 - Manifest Chain Consistency[/bold]: checks that generated artifacts are declared by parent manifests.",
    "phase2": "[bold]Phase 2 - On-Disk File Integrity[/bold]: checks files on disk against manifest hashes.",
}


def main() -> None:
    configure_script_logging(use_rich=True)
    parser = _build_parser()
    args = parser.parse_args()

    try:
        if args.command == "adapt":
            handle_adapt(args)
        elif args.command == "collect":
            handle_collect(args)
        elif args.command == "score-file":
            handle_score_file(args)
        elif args.command == "compare":
            if args.compare_command == "pareto-frontier":
                handle_pareto_frontier(args)
        elif args.command == "list-adapters":
            handle_list_adapters()
        else:
            config = _load_config(args.config)
            config_data_dir = config.get("data_dir")
            data_dir = resolve_data_dir(cli_arg=getattr(args, "data_dir", None), config_value=config_data_dir)
            config["data_dir"] = str(data_dir)
            config["_data_dir_source"] = get_data_dir_source(
                cli_arg=getattr(args, "data_dir", None), config_value=config_data_dir
            )
            if args.command == "config":
                handle_config(config)
            elif args.command == "list":
                handle_list(config)
            elif args.command == "ingest":
                handle_ingest(args, config)
            elif args.command == "score":
                handle_score(args, config)
            elif args.command == "analyze":
                handle_analyze(args, config)
            elif args.command == "verify":
                handle_verify(args, config)
    except RetroCastException as exc:
        logger.error("Command failed: %s", exc, exc_info=True)
        raise SystemExit(1) from exc


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=f"Retrocast CLI v{__version__}")
    parser.add_argument("--config", type=Path, default=Path("retrocast-config.yaml"), help="Path to config file")
    parser.add_argument("--data-dir", type=Path, help=f"Override data directory, or use {ENV_VAR_NAME}")
    parser.add_argument("--version", "-V", action="version", version=f"retrocast {__version__}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("config", help="Show resolved configuration and paths")
    subparsers.add_parser("list", help="List raw model manifests")
    subparsers.add_parser("list-adapters", help="List available adapters")

    adapt = subparsers.add_parser("adapt", help="Adapt raw planner output into v2 candidates")
    adapt.add_argument("--input", required=True, type=Path)
    adapt.add_argument("--output", required=True, type=Path)
    adapt.add_argument("--adapter", required=True)
    adapt.add_argument("--mode", choices=["strict", "prune"], default="strict")

    collect = subparsers.add_parser("collect", help="Collect v2 candidates by benchmark target")
    collect.add_argument("--input", required=True, type=Path)
    collect.add_argument("--benchmark", required=True, type=Path)
    collect.add_argument("--output", required=True, type=Path)

    score_file = subparsers.add_parser("score-file", help="Score collected candidates from explicit files")
    score_file.add_argument("--benchmark", required=True, type=Path)
    score_file.add_argument("--candidates", "--routes", dest="candidates", required=True, type=Path)
    score_file.add_argument("--stock", required=True, type=Path)
    score_file.add_argument("--output", required=True, type=Path)
    score_file.add_argument("--stock-name", help="Stock label to write into task constraints")
    score_file.add_argument("--model-name", help="Optional model label for manifest metadata")
    score_file.add_argument("--ignore-stereo", action="store_true", help="Use stereo-agnostic stock matching")

    compare_parser = subparsers.add_parser("compare", help="Compare schema v2 analysis reports")
    compare_subparsers = compare_parser.add_subparsers(dest="compare_command", required=True)
    pareto = compare_subparsers.add_parser("pareto-frontier", help="Plot metric against configured cost or time")
    pareto.add_argument("config", type=Path, help="YAML comparison config")
    pareto.add_argument("--time", action="store_true", help="Use wall_time_seconds instead of hourly_cost")
    pareto.add_argument("--no-open", action="store_true", help="Do not open the generated HTML")

    ingest = subparsers.add_parser("ingest", help="Project-mode v2 adapt plus collect")
    _add_model_dataset_args(ingest)
    ingest.add_argument("--adapter", help="Override adapter from raw manifest")
    ingest.add_argument("--mode", choices=["strict", "prune"], default="strict")
    ingest.add_argument("--no-progress", action="store_true", help="Disable progress bars during ingestion")

    score_parser = subparsers.add_parser("score", help="Score v2 processed candidates")
    _add_model_dataset_args(score_parser)
    score_parser.add_argument("--ignore-stereo", action="store_true", help="Use stereo-agnostic stock matching")

    analyze_parser = subparsers.add_parser("analyze", help="Analyze v2 evaluation artifacts")
    _add_model_dataset_args(analyze_parser)
    analyze_parser.add_argument("--stock", help="Specific stock to analyze")
    analyze_parser.add_argument("--top-k", nargs="+", type=int, default=[1, 3, 5, 10, 20, 50, 100])
    analyze_parser.add_argument("--n-boot", type=int, default=10000)

    verify_parser = subparsers.add_parser("verify", help="Verify artifact manifests and lineage")
    verify_target = verify_parser.add_mutually_exclusive_group(required=True)
    verify_target.add_argument("--target", type=Path, help="Manifest file or directory containing manifest.json")
    verify_target.add_argument("--all", action="store_true", help="Verify every manifest under the data directory")
    verify_parser.add_argument("--deep", action="store_true", help="Follow generated-artifact manifest links")
    verify_parser.add_argument("--strict", action="store_true", help="Treat missing files as failures")

    return parser


def _add_model_dataset_args(parser: argparse.ArgumentParser) -> None:
    model_group = parser.add_mutually_exclusive_group(required=True)
    model_group.add_argument("--model")
    model_group.add_argument("--all-models", action="store_true")
    dataset_group = parser.add_mutually_exclusive_group(required=True)
    dataset_group.add_argument("--dataset")
    dataset_group.add_argument("--all-datasets", action="store_true")


def _load_config(config_path: Path) -> dict[str, Any]:
    if not config_path.exists():
        return {}
    try:
        with open(config_path, encoding="utf-8") as handle:
            return yaml.safe_load(handle) or {}
    except yaml.YAMLError as exc:
        raise ConfigurationError(
            f"Failed to parse config file {config_path}",
            code="config.parse_error",
            context={"config_path": str(config_path)},
        ) from exc


def handle_adapt(args: argparse.Namespace) -> None:
    adapter = get_adapter(args.adapter)
    raw_payload = load_json_artifact(args.input)
    mode: AdaptMode = args.mode
    root_dir = args.output.parent.resolve()
    candidates = adapt_candidates(raw_payload, adapter, mode=mode)
    save_candidates(candidates, args.output)
    stats = candidate_statistics(candidates).to_manifest_dict()

    write_manifest(
        manifest_sidecar_path(args.output),
        action="[cli]adapt",
        sources=[args.input],
        outputs=[args.output],
        root_dir=root_dir,
        parameters={
            "adapter": normalize_adapter_slug(args.adapter),
            "mode": mode,
        },
        statistics=stats,
    )
    logger.info("Adapted v2 candidates to %s", args.output)


def handle_collect(args: argparse.Namespace) -> None:
    task = load_benchmark(args.benchmark)
    collected = collect_candidates(load_candidates(args.input), task)
    save_collected_candidates(collected, args.output)
    stats = collected_candidate_statistics(collected).to_manifest_dict()

    write_manifest(
        manifest_sidecar_path(args.output),
        action="[cli]collect",
        sources=[args.input, args.benchmark],
        outputs=[args.output],
        root_dir=args.output.parent.resolve(),
        statistics=stats,
    )
    logger.info("Collected v2 candidates to %s", args.output)


def handle_score_file(args: argparse.Namespace) -> None:
    stock_name = validate_filename(args.stock_name or _stock_name_from_path(args.stock), param_name="stock-name")
    task = _task_with_stock(load_benchmark(args.benchmark), stock_name)
    match_level = InChIKeyLevel.NO_STEREO if args.ignore_stereo else InChIKeyLevel.FULL
    evaluation = score(
        predictions=load_collected_candidates(args.candidates),
        task=task,
        constraint_checker=TaskConstraintChecker(
            stock=_load_stock_path(args.stock),
            stock_name=stock_name,
            match_level=match_level,
        ),
        acceptable_match_level=match_level,
    )
    save_evaluation(evaluation, args.output)
    write_manifest(
        manifest_sidecar_path(args.output),
        action="[cli]score-file",
        sources=[args.benchmark, args.candidates, args.stock],
        outputs=[args.output],
        root_dir=args.output.parent.resolve(),
        parameters={
            "stock": stock_name,
            "model_name": args.model_name,
            "ignore_stereo": args.ignore_stereo,
        },
        statistics=evaluation_statistics(evaluation),
    )
    logger.info("Scored collected candidates to %s", args.output)


def _stock_name_from_path(path: Path) -> str:
    for suffix in (".csv.gz", ".txt.gz", ".txt"):
        if path.name.endswith(suffix):
            return path.name.removesuffix(suffix)
    return path.stem


def _task_with_stock(task: Benchmark, stock_name: str) -> Benchmark:
    return task.model_copy(
        update={
            "default_constraints": task.default_constraints.model_copy(update={"stock": stock_name}),
            "constraints": {
                target_id: task.effective_constraints(target_id).model_copy(update={"stock": stock_name})
                for target_id in task.targets
            },
        }
    )


def _load_stock_path(path: Path) -> set[InChIKeyStr]:
    if path.name.endswith(".csv.gz"):
        return set(load_stock_file(path, return_as="inchikey"))
    if path.name.endswith(".txt.gz"):
        with gzip.open(path, "rt", encoding="utf-8") as handle:
            return _stock_inchikeys_from_lines(handle)
    if path.name.endswith(".txt"):
        return _stock_inchikeys_from_lines(path.read_text(encoding="utf-8").splitlines())
    raise InputError(
        "stock file must be .csv.gz, .txt.gz, or .txt",
        code="input.unsupported_format",
        context={"path": str(path), "supported_suffixes": [".csv.gz", ".txt.gz", ".txt"]},
    )


def _stock_inchikeys_from_lines(lines: Iterable[str]) -> set[InChIKeyStr]:
    return {InChIKeyStr(get_inchi_key(line.strip())) for line in lines if line.strip()}


def handle_ingest(args: argparse.Namespace, config: dict[str, Any]) -> None:
    paths = get_paths(Path(config.get("data_dir", DEFAULT_DATA_DIR)))
    models = _resolve_models(args, paths, stage="ingest")
    benchmarks = _resolve_benchmarks(args, paths)
    show_progress = not getattr(args, "no_progress", False)
    total_jobs = len(models) * len(benchmarks)

    if show_progress and total_jobs > 1:
        with create_cli_progress(console=console, unit="jobs") as progress, quiet_info_logs("retrocast"):
            task_id = progress.add_task("Ingesting model/dataset jobs", total=total_jobs)
            for model_name in models:
                for benchmark_name in benchmarks:
                    _ingest_one(model_name, benchmark_name, paths, args, show_route_progress=False)
                    progress.advance(task_id)
        return

    for model_name in models:
        for benchmark_name in benchmarks:
            _ingest_one(model_name, benchmark_name, paths, args, show_route_progress=show_progress)


def _ingest_one(
    model_name: str,
    benchmark_name: str,
    paths: dict[str, Path],
    args: argparse.Namespace,
    *,
    show_route_progress: bool,
) -> None:
    raw_dir = paths["raw"] / model_name / benchmark_name
    if not raw_dir.exists():
        logger.warning("Skipping %s/%s: raw directory missing", model_name, benchmark_name)
        return
    adapter_name = args.adapter or _manifest_directive(raw_dir / "manifest.json", "adapter")
    if adapter_name is None:
        logger.warning("Skipping %s/%s: no adapter in CLI or manifest", model_name, benchmark_name)
        return
    raw_filename = _manifest_directive(raw_dir / "manifest.json", "raw_results_filename") or "results.json.gz"
    raw_path = raw_dir / raw_filename
    if not raw_path.exists():
        logger.warning("Skipping %s/%s: raw file missing at %s", model_name, benchmark_name, raw_path)
        return

    task_path = paths["benchmarks"] / f"{benchmark_name}.json.gz"
    task = load_benchmark(task_path)
    raw_payload = load_json_artifact(raw_path)
    adapter = get_adapter(adapter_name)
    output_dir = paths["processed"] / benchmark_name / model_name
    output_dir.mkdir(parents=True, exist_ok=True)
    progress_total = estimate_raw_route_entries(
        raw_payload,
        input_kind="target-keyed-provider-output",
        benchmark_targets=task.targets,
    )

    with _route_progress(
        enabled=show_route_progress,
        description=f"Ingesting {model_name}/{benchmark_name}",
        total=progress_total,
    ) as advance_progress:
        collected = ingest_candidates(
            raw_payload=raw_payload,
            adapter=adapter,
            task=task,
            mode=args.mode,
            progress_callback=advance_progress,
        )

    output_path = output_dir / "candidates.json.gz"
    save_collected_candidates(collected, output_path)
    stats = collected_candidate_statistics(collected).to_manifest_dict()

    write_manifest(
        output_dir / "manifest.json",
        action="ingest:v2",
        sources=[raw_path, task_path],
        outputs=[output_path],
        root_dir=paths["raw"].parent.resolve(),
        parameters={
            "model": model_name,
            "benchmark": benchmark_name,
            "adapter": normalize_adapter_slug(adapter_name),
            "mode": args.mode,
        },
        statistics=stats,
    )
    logger.info("Ingested %s/%s to %s", model_name, benchmark_name, output_path)


def handle_score(args: argparse.Namespace, config: dict[str, Any]) -> None:
    paths = get_paths(Path(config.get("data_dir", DEFAULT_DATA_DIR)))
    for model_name in _resolve_models(args, paths, stage="score"):
        for benchmark_name in _resolve_benchmarks(args, paths):
            _score_one(model_name, benchmark_name, paths, args)


def _score_one(model_name: str, benchmark_name: str, paths: dict[str, Path], args: argparse.Namespace) -> None:
    task_path = paths["benchmarks"] / f"{benchmark_name}.json.gz"
    candidates_path = paths["processed"] / benchmark_name / model_name / "candidates.json.gz"
    if not candidates_path.exists():
        logger.warning("Skipping %s/%s: no processed candidates", model_name, benchmark_name)
        return

    predictions = load_collected_candidates(candidates_path)
    task = load_benchmark(task_path)
    stock_registry, stock_paths, output_label = _load_stock_registry(task, paths)
    match_level = InChIKeyLevel.NO_STEREO if args.ignore_stereo else InChIKeyLevel.FULL
    evaluation = score(
        predictions=predictions,
        task=task,
        constraint_checker=TaskConstraintChecker(
            stocks=stock_registry,
            match_level=match_level,
        ),
        acceptable_match_level=match_level,
    )

    output_dir = paths["scored"] / benchmark_name / model_name / output_label
    output_path = output_dir / "evaluation.json.gz"
    save_evaluation(evaluation, output_path)
    sources = [task_path, candidates_path, *stock_paths]
    write_manifest(
        output_dir / "manifest.json",
        action="score:v2",
        sources=sources,
        outputs=[output_path],
        root_dir=paths["raw"].parent.resolve(),
        parameters={
            "model": model_name,
            "benchmark": benchmark_name,
            "stock": output_label,
            "ignore_stereo": args.ignore_stereo,
        },
        statistics=evaluation_statistics(evaluation),
    )
    logger.info("Scored %s/%s using %s to %s", model_name, benchmark_name, output_label, output_path)


def handle_analyze(args: argparse.Namespace, config: dict[str, Any]) -> None:
    paths = get_paths(Path(config.get("data_dir", DEFAULT_DATA_DIR)))
    for model_name in _resolve_models(args, paths, stage="analyze"):
        for benchmark_name in _resolve_benchmarks(args, paths):
            _analyze_one(model_name, benchmark_name, paths, args)


def _analyze_one(model_name: str, benchmark_name: str, paths: dict[str, Path], args: argparse.Namespace) -> None:
    scored_base = paths["scored"] / benchmark_name / model_name
    if not scored_base.exists():
        logger.warning("Skipping %s/%s: no scored directory", model_name, benchmark_name)
        return
    stock_names = [args.stock] if args.stock else [path.name for path in scored_base.iterdir() if path.is_dir()]
    for stock_name in stock_names:
        evaluation_path = scored_base / stock_name / "evaluation.json.gz"
        if not evaluation_path.exists():
            logger.warning("Skipping missing evaluation %s", evaluation_path)
            continue
        evaluation = load_evaluation(evaluation_path)
        report = analyze(evaluation, ks=args.top_k, n_boot=args.n_boot)
        output_dir = paths["results"] / benchmark_name / model_name / stock_name
        analysis_path = output_dir / "analysis.json.gz"
        markdown_path = output_dir / "report.md"
        save_analysis_report(report, analysis_path)
        markdown_path.write_text(
            generate_markdown_report(
                report, title=f"Evaluation Report: {model_name} / {benchmark_name} / {stock_name}"
            ),
            encoding="utf-8",
        )
        write_manifest(
            output_dir / "manifest.json",
            action="analyze:v2",
            sources=[evaluation_path],
            outputs=[analysis_path, markdown_path],
            root_dir=paths["raw"].parent.resolve(),
            parameters={
                "model": model_name,
                "benchmark": benchmark_name,
                "stock": stock_name,
                "top_k": args.top_k,
                "n_boot": args.n_boot,
            },
            statistics={"n_metrics": len(report.metrics), "n_strata": len(report.by_stratum)},
        )
        console.print(
            create_analysis_table(report, title=f"Analysis Results: {model_name} / {benchmark_name} / {stock_name}")
        )
        console.print(f"\n[dim]Full report saved to: {output_dir}[/]\n")


def handle_config(config: dict[str, Any]) -> None:
    data_dir = Path(config.get("data_dir", DEFAULT_DATA_DIR))
    paths = get_paths(data_dir)
    console.print()
    console.print("[bold]RetroCast Schema V2 Configuration[/bold]")
    console.print("=" * 40)
    console.print(f"\n[bold]Data directory:[/bold] {data_dir.resolve()}")
    console.print(f"  Source: {config.get('_data_dir_source', 'unknown')}")
    console.print("\n[bold]Resolved paths:[/bold]")
    max_key_len = max(len(name) for name in paths)
    for name, path in paths.items():
        exists_marker = "[green]exists[/green]" if path.exists() else "[dim]missing[/dim]"
        console.print(f"  {name:<{max_key_len}}: {path} ({exists_marker})")
    console.print()


def handle_list(config: dict[str, Any]) -> None:
    paths = get_paths(Path(config.get("data_dir", DEFAULT_DATA_DIR)))
    raw_dir = paths["raw"]
    if not raw_dir.exists():
        console.print(f"[yellow]raw data directory does not exist: {raw_dir}[/]")
        return

    rows = []
    for manifest_path in sorted(raw_dir.glob("*/*/manifest.json")):
        model_name = manifest_path.parent.parent.name
        benchmark_name = manifest_path.parent.name
        try:
            model_name = validate_directory_name(model_name, param_name="model")
            benchmark_name = validate_directory_name(benchmark_name, param_name="benchmark")
            adapter_name = _manifest_directive(manifest_path, "adapter")
            raw_filename = _manifest_directive(manifest_path, "raw_results_filename") or "results.json.gz"
            rows.append((model_name, benchmark_name, adapter_name or "", raw_filename))
        except (OSError, json.JSONDecodeError, SecurityError) as exc:
            logger.debug("Skipping malformed raw manifest %s: %s", manifest_path, exc)

    if not rows:
        console.print(f"[yellow]no raw manifests found in {raw_dir}[/]")
        return

    table = Table(title=f"raw manifests: {raw_dir}")
    table.add_column("model")
    table.add_column("benchmark")
    table.add_column("adapter")
    table.add_column("raw file")
    for row in rows:
        table.add_row(*row)
    console.print(table)


def handle_list_adapters() -> None:
    console.print("Available adapters:")
    for name in sorted(ADAPTER_TYPES):
        console.print(f"  - {name}")
    aliases = ", ".join(f"{alias} -> {canonical}" for alias, canonical in sorted(DEPRECATED_ADAPTER_SLUGS.items()))
    if aliases:
        console.print(f"Deprecated aliases: {aliases}")


def handle_verify(args: argparse.Namespace, config: dict[str, Any]) -> None:
    data_dir = Path(config.get("data_dir", DEFAULT_DATA_DIR))
    manifest_paths = _resolve_manifest_paths(args, data_dir)

    reports = []
    with create_cli_progress(console=console, unit="manifests") as progress:
        task_id = progress.add_task("Verifying manifests", total=len(manifest_paths))
        with quiet_info_logs("retrocast"):
            for manifest_path in manifest_paths:
                reports.append(
                    verify_manifest(
                        manifest_path=manifest_path,
                        root_dir=data_dir,
                        deep=args.deep,
                        lenient=not args.strict,
                    )
                )
                progress.advance(task_id)

    if len(reports) == 1:
        _print_verification_report(reports[0])
    else:
        _print_verification_issue_summary(reports)
        _print_verification_batch_result(reports)

    if any(not report.is_valid for report in reports):
        raise SystemExit(1)


def _resolve_manifest_paths(args: argparse.Namespace, data_dir: Path) -> list[Path]:
    if args.all:
        manifest_paths = sorted(data_dir.glob("**/manifest.json"))
        if not manifest_paths:
            logger.warning("No manifests found under %s", data_dir)
        return manifest_paths

    target = Path(args.target)
    if target.is_dir():
        return [target / "manifest.json"]
    return [target]


def _print_verification_report(report: VerificationReport) -> None:
    color = "green" if report.is_valid else "red"
    lines = _verification_overview_lines(report)
    for issue in report.issues:
        level = {
            "PASS": "[green]✓ PASS[/green]",
            "INFO": "[blue]ℹ INFO[/blue]",
            "WARN": "[yellow]⚠ WARN[/yellow]",
            "FAIL": "[red]✗ FAIL[/red]",
        }[issue.level]
        category = f" [{issue.category}]" if issue.category else ""
        lines.append(f"{level}{category}: {issue.message}")
        lines.append(f"  Path: [dim]{issue.path}[/dim]\n")
    if not lines:
        lines.append("[green]✓ No issues found[/green]")
    console.print(Panel("\n".join(lines), title=f"Verification Report: {report.manifest_path}", border_style=color))


def _verification_overview_lines(report: VerificationReport) -> list[str]:
    categories = {issue.category for issue in report.issues if issue.category}
    if len(categories) <= 1 and "phase1" not in categories:
        return []

    lines = ["[bold]Verification Process Overview:[/bold]\n"]
    for key in ("graph", "primary", "phase1", "phase2"):
        if key == "primary" or key in categories:
            lines.append(VERIFICATION_EXPLANATIONS[key])
    lines.append("")
    return lines


def _print_verification_issue_summary(reports: list[VerificationReport]) -> None:
    issue_rows = [
        (report.manifest_path, issue)
        for report in reports
        for issue in report.issues
        if issue.level in {"FAIL", "WARN"}
    ]
    if not issue_rows:
        return

    table = Table(title="verification issues")
    table.add_column("level", no_wrap=True)
    table.add_column("manifest")
    table.add_column("path")
    table.add_column("message")
    for manifest_path, issue in issue_rows:
        level = "[red]fail[/red]" if issue.level == "FAIL" else "[yellow]warn[/yellow]"
        table.add_row(level, str(manifest_path), str(issue.path), issue.message)
    console.print(table)


def _print_verification_batch_result(reports: list[VerificationReport]) -> None:
    total = len(reports)
    valid_count = sum(1 for report in reports if report.is_valid)
    if valid_count == total:
        console.print(f"[bold green]✓ All {total} manifests verified successfully.[/]")
        return

    console.print(f"[bold yellow]⚠ {total - valid_count} of {total} manifests failed verification.[/]")
    for report in reports:
        if not report.is_valid:
            console.print(f"  [red]✗[/red] {report.manifest_path}")


def _resolve_models(args: argparse.Namespace, paths: dict[str, Path], *, stage: str) -> list[str]:
    if getattr(args, "model", None):
        return [validate_directory_name(args.model, param_name="model")]
    if stage == "ingest":
        base = paths["raw"]
    elif stage == "score":
        base = paths["processed"]
    else:
        base = paths["scored"]
    if not base.exists():
        return []

    models = set()
    for top_level_dir in base.iterdir():
        if not top_level_dir.is_dir():
            continue
        if stage == "ingest":
            models.add(top_level_dir.name)
        else:
            for model_dir in top_level_dir.iterdir():
                if model_dir.is_dir():
                    models.add(model_dir.name)
    return sorted(validate_directory_name(model, param_name="model") for model in models)


def _resolve_benchmarks(args: argparse.Namespace, paths: dict[str, Path]) -> list[str]:
    if getattr(args, "dataset", None):
        return [validate_filename(args.dataset, param_name="dataset")]
    if not paths["benchmarks"].exists():
        return []
    return sorted(
        validate_filename(path.name.removesuffix(".json.gz"), param_name="dataset")
        for path in paths["benchmarks"].glob("*.json.gz")
    )


def _manifest_directive(path: Path, key: str) -> str | None:
    if not path.exists():
        return None
    with open(path) as handle:
        payload = json.load(handle)
    value = payload.get("directives", {}).get(key)
    return str(value) if value is not None else None


def _load_stock_registry(
    task: Benchmark,
    paths: dict[str, Path],
) -> tuple[dict[str, set[InChIKeyStr]], list[Path], str]:
    stock_names = _effective_stock_names(task)
    stock_paths = []
    stock_registry = {}
    for stock_name in sorted(stock_names):
        stock_path = paths["stocks"] / f"{stock_name}.csv.gz"
        stock_registry[stock_name] = set(load_stock_file(stock_path, return_as="inchikey"))
        stock_paths.append(stock_path)

    return stock_registry, stock_paths, task.derived_metric_label()


def _effective_stock_names(task: Benchmark) -> set[str]:
    stock_names = set()
    for target_id in task.targets:
        stock = task.effective_constraints(target_id).stock
        if stock is not None:
            stock_names.add(stock)
    return stock_names


@contextmanager
def _route_progress(
    *,
    enabled: bool,
    description: str,
    total: int | None,
) -> Iterator[Callable[[], None] | None]:
    if not enabled:
        yield None
        return

    with create_cli_progress(console=console, unit="routes") as progress, quiet_info_logs("retrocast"):
        task_id = progress.add_task(description, total=total)
        yield lambda: progress.advance(task_id)


if __name__ == "__main__":
    main()
